services:
  backend:
    restart: always
    ports:
      - "127.0.0.1:${BACKEND_PORT:-4000}:${BACKEND_PORT:-4000}"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  frontend:
    restart: always
    ports:
      - "127.0.0.1:${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  cms:
    restart: always
    ports:
      - "127.0.0.1:${CMS_PORT:-3001}:${CMS_PORT:-3001}"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  postgres:
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

  nginx:
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  db-backup:
    restart: always

  certbot:
    restart: always
